import type { FacilityDefinition } from '../../types/content'

export const facilityDefinitions: FacilityDefinition[] = [
  {
    id: 'dungeon_core',
    name: '던전 코어',
    shortName: '코어',
    description: '던전 전체를 유지하는 심장부입니다.',
    category: 'core',
    buildable: false,
    requiredTier: 1,
    buildCost: {},
    levels: [{ level: 1, dailyEffects: [] }],
    tags: ['unique', 'core'],
    requirements: [],
  },
  {
    id: 'quarters',
    name: '숙소',
    shortName: '숙소',
    description: '주민들이 몸을 누일 수 있는 공동 숙소입니다.',
    category: 'housing',
    buildable: true,
    requiredTier: 1,
    buildCost: { material: 20 },
    levels: [
      { level: 1, dailyEffects: [], populationCapacity: 5, upgradeCost: { material: 30 } },
      { level: 2, dailyEffects: [], populationCapacity: 10, upgradeCost: { material: 50 } },
      { level: 3, dailyEffects: [], populationCapacity: 18 },
    ],
    tags: ['housing'],
    requirements: [],
  },
  {
    id: 'mine',
    name: '채굴장',
    shortName: '채굴장',
    description: '암반을 깎아 건설에 필요한 자재를 생산합니다.',
    category: 'production',
    buildable: true,
    requiredTier: 1,
    buildCost: { material: 25 },
    levels: [
      { level: 1, dailyEffects: [{ type: 'addResource', resourceId: 'material', amount: 6 }], staffSlots: 2, upgradeCost: { material: 35 } },
      { level: 2, dailyEffects: [{ type: 'addResource', resourceId: 'material', amount: 10 }], staffSlots: 3, upgradeCost: { material: 55 } },
      { level: 3, dailyEffects: [{ type: 'addResource', resourceId: 'material', amount: 16 }], staffSlots: 4 },
    ],
    tags: ['production', 'labor', 'physical', 'material'],
    requirements: [],
  },
  {
    id: 'fungus_farm',
    name: '균사 농장',
    shortName: '농장',
    description: '어둠에서도 자라는 균류를 재배합니다.',
    category: 'production',
    buildable: true,
    requiredTier: 1,
    buildCost: { material: 20 },
    levels: [
      { level: 1, dailyEffects: [{ type: 'addResource', resourceId: 'food', amount: 8 }], staffSlots: 2, upgradeCost: { material: 30 } },
      { level: 2, dailyEffects: [{ type: 'addResource', resourceId: 'food', amount: 13 }], staffSlots: 3, upgradeCost: { material: 45 } },
      { level: 3, dailyEffects: [{ type: 'addResource', resourceId: 'food', amount: 20 }], staffSlots: 4 },
    ],
    tags: ['production', 'labor', 'food'],
    requirements: [],
  },
  {
    id: 'mana_chamber',
    name: '마력실',
    shortName: '마력실',
    description: '지맥의 흐름에서 마력을 모읍니다.',
    category: 'production',
    buildable: true,
    requiredTier: 3,
    buildCost: { material: 30 },
    levels: [
      { level: 1, dailyEffects: [{ type: 'addResource', resourceId: 'mana', amount: 4 }], staffSlots: 1, upgradeCost: { material: 40, mana: 10 } },
      { level: 2, dailyEffects: [{ type: 'addResource', resourceId: 'mana', amount: 7 }], staffSlots: 2, upgradeCost: { material: 60, mana: 20 } },
      { level: 3, dailyEffects: [{ type: 'addResource', resourceId: 'mana', amount: 11 }], staffSlots: 3 },
    ],
    tags: ['production', 'mana'],
    requirements: [],
  },
  {
    id: 'warehouse',
    name: '창고',
    shortName: '창고',
    description: '각종 자원을 안전하게 보관합니다.',
    category: 'storage',
    buildable: true,
    requiredTier: 2,
    buildCost: { material: 20 },
    levels: [
      { level: 1, dailyEffects: [], storageCapacity: { gold: 200, material: 150, food: 100, mana: 100 }, upgradeCost: { material: 30 } },
      { level: 2, dailyEffects: [], storageCapacity: { gold: 400, material: 300, food: 200, mana: 200 }, upgradeCost: { material: 50 } },
      { level: 3, dailyEffects: [], storageCapacity: { gold: 800, material: 600, food: 400, mana: 400 } },
    ],
    tags: ['storage'],
    requirements: [],
  },
  {
    id: 'guard_post',
    name: '경비실',
    shortName: '경비실',
    description: '경비병이 침입에 대비하는 방어 거점입니다.',
    category: 'defense',
    buildable: true,
    requiredTier: 1,
    buildCost: { gold: 10, material: 30 },
    levels: [
      { level: 1, dailyEffects: [], defense: 15, staffSlots: 2, upgradeCost: { gold: 20, material: 40 } },
      { level: 2, dailyEffects: [], defense: 25, staffSlots: 3, upgradeCost: { gold: 35, material: 60 } },
      { level: 3, dailyEffects: [], defense: 40, staffSlots: 4 },
    ],
    tags: ['defense', 'combat'],
    requirements: [],
  },
  {
    id: 'trap_room',
    name: '함정실',
    shortName: '함정실',
    description: '마력으로 작동하는 장치가 침입자를 저지합니다.',
    category: 'defense',
    buildable: true,
    requiredTier: 2,
    buildCost: { material: 25, mana: 10 },
    levels: [
      { level: 1, dailyEffects: [], maintenanceEffects: [{ type: 'addResource', resourceId: 'mana', amount: -1 }], defense: 20, upgradeCost: { material: 35, mana: 15 } },
      { level: 2, dailyEffects: [], maintenanceEffects: [{ type: 'addResource', resourceId: 'mana', amount: -2 }], defense: 35, upgradeCost: { material: 50, mana: 25 } },
      { level: 3, dailyEffects: [], maintenanceEffects: [{ type: 'addResource', resourceId: 'mana', amount: -3 }], defense: 55 },
    ],
    tags: ['defense', 'trap', 'magical'],
    requirements: [],
  },
  {
    id: 'training_ground',
    name: '훈련장',
    shortName: '훈련장',
    description: '경비병이 실전에 대비해 전투 진형을 연습합니다.',
    category: 'defense',
    buildable: true,
    requiredTier: 3,
    buildCost: { material: 35, gold: 15 },
    levels: [
      { level: 1, dailyEffects: [], staffSlots: 1, modifiers: [{ type: 'combatContributionMultiplier', value: 1.1 }], upgradeCost: { material: 30, gold: 20 } },
      { level: 2, dailyEffects: [], staffSlots: 1, modifiers: [{ type: 'combatContributionMultiplier', value: 1.18 }], upgradeCost: { material: 45, gold: 30 } },
      { level: 3, dailyEffects: [], staffSlots: 1, modifiers: [{ type: 'combatContributionMultiplier', value: 1.25 }] },
    ],
    tags: ['defense', 'combat', 'training'],
    requirements: [],
  },
  {
    id: 'watch_post',
    name: '감시소',
    shortName: '감시소',
    description: '던전 통로를 감시하고 침입자의 진입을 늦춥니다.',
    category: 'defense',
    buildable: true,
    requiredTier: 3,
    buildCost: { material: 30, gold: 15 },
    levels: [
      { level: 1, dailyEffects: [], defense: 8, upgradeCost: { material: 30, gold: 15 } },
      { level: 2, dailyEffects: [], defense: 14, upgradeCost: { material: 45, gold: 25 } },
      { level: 3, dailyEffects: [], defense: 22 },
    ],
    tags: ['defense', 'watch', 'invasion_forecast'],
    requirements: [],
  },
  {
    id: 'infirmary',
    name: '치료소',
    shortName: '치료소',
    description: '부상자를 돌보아 침입 패배 시 주민 손실을 줄입니다.',
    category: 'housing',
    buildable: true,
    requiredTier: 4,
    buildCost: { material: 40, gold: 25 },
    levels: [
      { level: 1, dailyEffects: [], modifiers: [{ type: 'residentLossChanceMultiplier', value: 0.8 }], upgradeCost: { material: 35, gold: 20 } },
      { level: 2, dailyEffects: [], modifiers: [{ type: 'residentLossChanceMultiplier', value: 0.6 }], upgradeCost: { material: 50, gold: 30 } },
      { level: 3, dailyEffects: [], modifiers: [{ type: 'residentLossChanceMultiplier', value: 0.4 }] },
    ],
    tags: ['support', 'recovery', 'population_protection'],
    requirements: [],
  },
  {
    id: 'mana_reservoir',
    name: '마력 저장고',
    shortName: '마력고',
    description: '고밀도 마력을 안정적으로 모으는 상위 생산 시설입니다.',
    category: 'production',
    buildable: true,
    requiredTier: 4,
    buildCost: { material: 45, mana: 20 },
    levels: [
      { level: 1, dailyEffects: [{ type: 'addResource', resourceId: 'mana', amount: 5 }], staffSlots: 1, upgradeCost: { material: 40, mana: 20 } },
      { level: 2, dailyEffects: [{ type: 'addResource', resourceId: 'mana', amount: 9 }], staffSlots: 2, upgradeCost: { material: 60, mana: 30 } },
      { level: 3, dailyEffects: [{ type: 'addResource', resourceId: 'mana', amount: 14 }], staffSlots: 3 },
    ],
    tags: ['production', 'mana', 'advanced'],
    requirements: [],
  },
  {
    id: 'reinforced_gate',
    name: '강화 관문',
    shortName: '관문',
    description: '중무장 경비병이 침입자를 정면에서 막는 견고한 관문입니다.',
    category: 'defense',
    buildable: true,
    requiredTier: 4,
    buildCost: { material: 55, gold: 30 },
    levels: [
      { level: 1, dailyEffects: [], defense: 25, staffSlots: 2, upgradeCost: { material: 50, gold: 30 } },
      { level: 2, dailyEffects: [], defense: 38, staffSlots: 3, upgradeCost: { material: 70, gold: 45 } },
      { level: 3, dailyEffects: [], defense: 55, staffSlots: 4 },
    ],
    tags: ['defense', 'combat', 'gate'],
    requirements: [],
  },
]

export const facilityDefinitionById = Object.fromEntries(
  facilityDefinitions.map((facility) => [facility.id, facility]),
) as Record<string, FacilityDefinition>
